# Generated by Django 3.0.6 on 2020-05-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='xray_2',
        ),
        migrations.AddField(
            model_name='appointment',
            name='other',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
