# Generated by Django 3.0.4 on 2020-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0003_auto_20200510_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ("don't wanna tell", "don't wanna tell")], default='male', max_length=100),
        ),
    ]
