# Generated by Django 3.0.4 on 2020-05-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0005_auto_20200516_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
