# Generated by Django 3.0.4 on 2020-05-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0007_remove_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ("don't wanna tell", "don't wanna tell")], default='male', max_length=100),
        ),
    ]
