# Generated by Django 3.0.4 on 2020-05-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0008_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(default='doctor-1', max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
