# Generated by Django 3.0.4 on 2020-05-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0011_auto_20200517_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='other',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
