# Generated by Django 3.0.4 on 2020-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0012_auto_20200517_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
