# Generated by Django 3.0.4 on 2020-05-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0013_auto_20200517_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
