# Generated by Django 3.0.4 on 2020-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0014_auto_20200517_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='xray_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(choices=[('Doctor-1', 'Doctor-1'), ('Doctor-2', 'Doctor-2'), ('Doctor-3', 'Doctor-3')], default='doctor-1', max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Blank', 'Blank')], default='male', max_length=100),
        ),
    ]
