# Generated by Django 3.0.4 on 2020-05-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0015_auto_20200518_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctorname',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_patient.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('General', 'General'), ('Urgent', 'Urgent'), ('Regular Checkup', 'Regular Checkup')], default='General', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treated_or_not',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mob',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_patient.Patient')),
            ],
        ),
    ]
