# Generated by Django 3.0.4 on 2020-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0020_auto_20200522_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpeg', null=True, upload_to=''),
        ),
    ]
