# Generated by Django 3.0.4 on 2020-05-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0021_auto_20200523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/profile.jpeg', null=True, upload_to='images/'),
        ),
    ]
