# Generated by Django 3.0.4 on 2020-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0022_auto_20200523_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_call_url', models.URLField(max_length=100, null=True)),
            ],
        ),
    ]
