# Generated by Django 3.0.4 on 2020-05-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0023_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_patient.Appointment'),
        ),
    ]
