# Generated by Django 3.0.4 on 2020-05-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0024_url_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='notification',
        ),
    ]
