# Generated by Django 3.0.4 on 2020-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0025_auto_20200527_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
