# Generated by Django 3.0.4 on 2020-06-04 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0027_auto_20200604_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique ID for this appointment'),
        ),
    ]
