# Generated by Django 3.0.4 on 2020-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0028_appointment_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.CharField(default='Virtual Dental Clinic', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Blank', 'Blank')], default='male', max_length=100),
        ),
    ]
