# Generated by Django 3.0.4 on 2020-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_patient', '0030_prescription_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='sex',
            field=models.CharField(default='male', max_length=100),
        ),
    ]
